rs.setOutput("back", true)
sleep(1.5)
rs.setOutput("back", false)
sleep(0.5)
rs.setOutput("left", true)
rs.setOutput("right", true)
sleep(0.5)
rs.setOutput("left", false)
rs.setOutput("right", false)
shell.run("reboot")